### ISSUE TITLE
imagerotate does not return an image in certain cases, no error handling

### ISSUE THREAD

**Issue by auge8472** [My-Little-Forum/mylittleforum#658]
In certain cases the function `imagerotate`, utilised in the function `create_image` in `modules/captcha/captcha.php` does not return an image in case of the angle value of 180 degrees (second function parameter). Independently from solving the possible bug itself (there is none [in a first sight](https://github.com/ilosuna/mylittleforum/blob/8fe0b4ed02c431289d72f0fd45067dce423523cc/modules/captcha/captcha.php#L83)) we basically need an error handling (handling of the value `false`). What should be done, if the fuction fails? IMHO the unrotated image should be used instead.

See therefore [this thread in the project forum](https://mylittleforum.net/forum/index.php?id=14994)

**Comment by loesler** [comment]
I do not use this /feature/ Do we really need it anymore (accessibility)?

**Comment by auge8472** [comment]
> I do not use this *feature*. Do we really need it anymore (accessibility)?

See therfore [my new reply](https://mylittleforum.net/forum/index.php?id=15009) to the discussion previously linked above. :-)

**Comment by vihuna** [comment]
I have tested the changes made in PR #668: they seem to solve the problem, at least in my case, whatever the problem with `imagerotate` + 180º was.

**Comment by auge8472** [comment]
@vihuna Thank you for your effort. I'll merge the change today in the evening (CET).

**Comment by auge8472** [comment]
I'll close this issue for now. We'll have a release, that includes the changes of the corresponding PR #668 within the next days. If we get a report about ongoing errors, we can reopen this issue or open a new one.
