### ISSUE TITLE
IPv6 addresses are too long for database column

### ISSUE THREAD

**Issue by lfuerderer** [My-Little-Forum/mylittleforum#681]
When I access the forum over IPv6, a php error is thrown, because my client ip address does not fit into the database field (`mlf2_useronline.ip` with type `char(15)`)

error message:
```
PHP Fatal error:  Uncaught mysqli_sql_exception: Data too long for column 'ip' at row 1 in /var/www/html/includes/functions.inc.php:1232
Stack trace:
#0 /var/www/html/includes/functions.inc.php(1232): mysqli_query()
#1 /var/www/html/includes/main.inc.php(263): user_online()
#2 /var/www/html/index.php(36): include('...')
#3 {main}
  thrown in /var/www/html/includes/functions.inc.php on line 1232
```

I use version 20220803.1 of mylittleforum
[see the error location in the code](https://github.com/My-Little-Forum/mylittleforum/blob/8fe0b4ed02c431289d72f0fd45067dce423523cc/includes/functions.inc.php#L1232)

I think, the type of the `ip` column should be `char(39)` so that every IPv4 and IPv6 address can fit in.

**Comment by auge8472** [comment]
Your observation is correct. We discussed the issue of HTTP-status 500 for *some* users of a few forums in *some* cases and came to the same conclusion. See the following [entry in the project forum](https://mylittleforum.net/forum/index.php?mode=thread&id=15805) and the complete thread for details.

Nevertheless thank you for your investigation and report.
