### ISSUE TITLE
Unverified use of the variable `$categories`

### ISSUE THREAD

**Issue by auge8472** [My-Little-Forum/mylittleforum#685]
In [line 66 of the script `thread.inc.php`](https://github.com/My-Little-Forum/mylittleforum/blob/20220803.1/includes/thread.inc.php#L66) the variable `$categories`is used without checking if it exists beforehand. Because the definition of categories in a forum is optional, this will cause an error if no categories are defined.

See also the discussion in #684 beginning with [this comment](https://github.com/My-Little-Forum/mylittleforum/issues/684#issuecomment-1905486139).

**Comment by loesler** [comment]
An if-statement like in [index.inc.php](https://github.com/My-Little-Forum/mylittleforum/blob/master/includes/index.inc.php#L115) was added to solve this issue, cf. https://github.com/My-Little-Forum/mylittleforum/pull/687
