### ISSUE TITLE
Verbose error reporting in the captcha module

### ISSUE THREAD

**Issue by auge8472** [My-Little-Forum/mylittleforum#688]
I inserted the code for the verbose error reporting temporarily for testing the changes in PR #668. Even @loesler [pointed out the code to me](https://github.com/My-Little-Forum/mylittleforum/pull/668#pullrequestreview-1345497223) to remove it before merging, I forgot to remove the change.

I would like to keep the line in itself but to comment it out.

**Comment by loesler** [comment]
> I would like to keep the line in itself but to comment it out.

Perfect.
