### ISSUE TITLE
Add new BB-codes for HTML-elements <ins>, <del> and maybe <s>

### ISSUE THREAD

**Issue by auge8472** [My-Little-Forum/mylittleforum#697]
Writing an entry about testing a new script, I came across the need to transparently document changes inside the forum entry. Therefore I wanted to use the HTML-elements `ins` and `del`, but realised that there are no BB-codes for this. This might not be a common task but IMHO nothing speaks against providing buttons and BB-codes for this purpose.

Maybe it would be a good idea, to provide an additional BB-code for `s` (strike through) independently from `del`. These two HTML-elements have different meaning [^1], even both have the same visual formatting at least in the common desktop browsers.

It's questionable if the buttons for these BB-codes should be displayed per default or if should be hidden behind a setting switch.

[^1]: `s` = text with a strike through line, `del` = outdated text, possibly replaced by text in `ins` (subsequently inserted text)

**Comment by loesler** [comment]
We can add BB support even if a button is not shown like for the tag [pre]

**Comment by auge8472** [comment]
> We can add BB support even if a button is not shown like for the tag `[pre]`

I know this. :-) 

I will add the codes without buttons. However, I'll create a wiki page to document the existing BB-Codes.

**Comment by auge8472** [comment]
done with #699
