### ISSUE TITLE
Error when manually marking a posting as ham

### ISSUE THREAD

**Issue by auge8472** [My-Little-Forum/mylittleforum#745]
Got an error in my testing installation (upgraded from 2.4.20 via 20240729.1 to 20240827.1).

**Fatal error: Uncaught Error: Call to a member function learn() on null in /forum-dir/includes/posting.inc.php:1878 Stack trace: #0 /forum-dir/index.php(153): include() #1 {main} thrown in /forum-dir/includes/posting.inc.php on line 1878**

[This is line 1878 in posting.inc.php](https://github.com/My-Little-Forum/mylittleforum/blob/20240827.1/includes/posting.inc.php#L1878).

**Notice**: I did not encounter a similar error in the project forum.

**Comment by loesler** [comment]
Is the instance, i.e. $B8_BAYES_FILTER, available?

**Comment by auge8472** [comment]
> Is the instance, i.e. $B8_BAYES_FILTER, available?

I didn't check the code in itself but I compared the file dates and sizes and found out, that I forgot to upload the files `index.php` and `includes/functions.inc.php` during the upgrade (And that to me! 😄). After doing this, the error is gone. Thank you for pointing me indirectly to possibly wrong file versions.
