### ISSUE TITLE
Check for existing user name is inaccurate

### ISSUE THREAD

**Issue by auge8472** [My-Little-Forum/mylittleforum#750]
If I, as a forum administrator, want to edit a posting of a not registered visitor with the same name as a registered user, I get an error message after submitting my changes, that tells me, that the author name is in use by another _registered_ user. To be more precise, in _this_ case the error is triggered by the fact that the user who wrote the post has registered after writing the post in question, thereby blocking the username from being used by other users. It could just as well be that they are obviously two different people. That is the same thing in the endeffent.

Now, when I tried to edit the post, I was hit by this lock.

The check [as it is implemented](https://github.com/My-Little-Forum/mylittleforum/blob/20240827.1/includes/posting.inc.php#L784) only asks for the user name.

```sql
SELECT
    user_id,
    user_name
FROM mlf2_userdata
WHERE lower(user_name) = 'john doe' -- the value also gets lowered
```

It IMHO also should compare the posting time with the time of registration because the name may have been in use before.

```sql
SELECT
    user_id,
    user_name
FROM mlf2_userdata
WHERE lower(user_name) = 'john doe'
    AND registered > 'posting_time' -- check for registration after the time of posting creation
```

Have I missed anything?

**Comment by loesler** [comment]
- Yes, I think an admin/mod must always have the right to edit a post.
- Suggestion: https://github.com/My-Little-Forum/mylittleforum/pull/751
- However, your modification should also be added (in case the user edits their own post. I'll leave it to you)

**Comment by auge8472** [comment]
After the pull requests #751 and #776 are merged, the issue is solved.
